redis:
  port: 6379
  host: localhost

port: 3001
wsport: 3000

google_search:
  base_url: https://www.google.co.uk
  fetch_top_x_results: 9

fetch_cache:
  expiration: 604800 # pages expire in one week

save_to_disk: false

routes:
  home: '/'
  batch: '/batch'
  queryByEmail: '/api/v1/search/email'
  queryByEmailBatch: '/api/v1/search/emailBatch'
  batchProgress: '/api/v1/batch_progress'
